"""Обновил constraint базовой модели и __repr__ в остальных моделях

Revision ID: 01323f40685e
Revises: 2dd388abf4c4
Create Date: 2024-08-12 20:21:27.097712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01323f40685e'
down_revision = '2dd388abf4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
