"""First

Revision ID: 7ac85faf5a23
Revises: 9de32e051ec9
Create Date: 2024-06-27 20:22:41.635300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac85faf5a23'
down_revision = '9de32e051ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
